model:
  #name: "TinyLlama/TinyLlama-1.1B-Chat-v1.0"
  #name: "EleutherAI/gpt-neo-125M"
  #name: "Qwen/Qwen3-4B-Thinking-2507"
  #name: "deepseek-ai/DeepSeek-R1-Distill-Llama-70B"
  #name: "Qwen/Qwen2-72B-Instruct"
  #name: "Qwen/Qwen2.5-14B-Instruct"
  #name: "Qwen/Qwen2.5-32B-Instruct"
  #name: "Qwen/Qwen2.5-72B-Instruct"
  #name: "meta-llama/Llama-3.3-70B-Instruct"
  #name: "openai/gpt-oss-20b"
  #name: "mistralai/Mistral-Small-3.2-24B-Instruct-2506"
  #name: "meta-llama/Llama-3.1-8B"
  #name: "gpt-4o"
  #name: aws-prototyping/MegaBeam-Mistral-7B-512k
  #name : google/gemma-3-1b-pt
  #name: mistralai/Mistral-7B-Instruct-v0.3
  name: mistralai/Mistral-7B-v0.3
  device: "auto"
  dtype: "auto"
  is_chat_model: false

chat:
  system_prompt: "You are a professional journalist specializing in writing news.
                  Follow the given structure."


quantization:
  mode: "none"
  #mode: "4bit"
  #mode: "8bit"

  bnb_4bit_quant_type: "nf4"
  bnb_4bit_use_double_quant: true
  bnb_4bit_compute_dtype: "bfloat16"

  llm_int8_enable_fp32_cpu_offload: false
  llm_int8_has_fp16_weight: false
  llm_int8_threshold: 6.0
  offload_folder: "offload"
  # max_memory:
  #   cuda: "46GiB"
  #   cpu: "128GiB"


decoding:
  temperature: 0.7
  top_p: 0.92
  top_k: 50
  repetition_penalty: 1.05
  #max_new_tokens: 32768
  max_new_tokens: 200 # For testing purposes
  do_sample: true
  num_return_sequences: 1
  num_beams: 1


news:
  length_min: 80
  length_max: 140
